---
title: "GIS Project"
output: html_notebook
---


```{r}
#install.packages("rgeoprofile")
library(rgeoprofile)
```

```{r}
#install.packages("mobr")
library(mobr)
data("desalvo")
desavlo_coordinates = data.frame("lat" = desalvo$lat, "lon" = desalvo$lon)
#sum(avg_nn_dist(desavlo_coordinates))
nn = c()
for (i in 1:length(desalvo$name)-1){
  long = desalvo$lon[13] - desalvo$lon[i]
  lat = desalvo$lat[13] - desalvo$lat[i]
  nn[i] =abs(long)*111139+abs(lat)*111139#111139

}
sum(nn)
```

```{r}
cgt
```


```{r}


cgt = cgt_profile(desalvo$lat, desalvo$lon,buffer = 10,f=0.2,g=80, n=3000)
```




```{r}
g_map = sp::SpatialPixelsDataFrame(points = cgt[c("lons", "lats")], data = cgt)
g_map <- raster::raster(g_map)
# Assign a Coordinate Reference System for the Raster
raster::crs(g_map) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")


library(leaflet) #for mapping the geographic profile
pal <- colorNumeric(pals::parula(100), raster::values(g_map),
                    na.color = "transparent")

# Map 
cgt_map <- leaflet(width = "50%") %>%
  addProviderTiles('Esri.WorldTopoMap', group = 'Topo') %>%
  addAwesomeMarkers(lng = -71.07357, lat = 42.41322, icon = awesomeIcons(
    icon = 'home', markerColor = 'green'), popup = 'Residence') %>%
  addRasterImage(g_map, colors = pal, opacity = 0.8) %>%
  addLegend(pal = pal, values = raster::values(g_map), title = 'Score') %>%
  addCircleMarkers(lng = desalvo$lon, lat = desalvo$lat, radius = 4, opacity = 1,
                   stroke = FALSE, fillOpacity = 0.9, weight = 2,
                   fillColor = "black")
cgt_map
```





```{r}
ne_1 <- neg_exp_profile(desalvo$lat, desalvo$lon, buffer = TRUE, method = "custom",a=0.5,b=-0.2 ,n =3000)

```

```{r}
g_map1 = sp::SpatialPixelsDataFrame(points = ne_1[c("lons", "lats")], data = ne_1)
g_map1 <- raster::raster(g_map1)
raster::crs(g_map1) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
pal1 <- colorNumeric(pals::parula(200), raster::values(g_map1),
                    na.color = "transparent")
ne_crimestat_map <- leaflet() %>%
  addProviderTiles('Esri.WorldTopoMap', group = 'Topo') %>%
  addAwesomeMarkers(lng = -71.07357, lat = 42.41322, icon = awesomeIcons(
    icon = 'home', markerColor = 'green'), popup = 'Residence') %>%
  addRasterImage(g_map1, colors = pal1, opacity = 0.6) %>%
  addLegend(pal = pal1, values = raster::values(g_map1), title = 'Score') %>%
  addCircleMarkers(lng = desalvo$lon, lat = desalvo$lat, radius = 4, opacity = 1,
                   stroke = FALSE, fillOpacity = 0.75, weight = 2,
                   fillColor = "black")

ne_crimestat_map
```



```{r}
cmd_pred(desalvo$lat, desalvo$lon)
```





```{r}
install.packages(bobverity)
library(bobverity)
data(LondonExample_crimes)
```


```{r}
linear <- linear_profile(desalvo$lat, desalvo$lon, a = 1.9, b = -0.05, n=3000)

```



```{r}
g_map_lin = sp::SpatialPixelsDataFrame(points = linear[c("lons", "lats")], data = linear)
g_map_lin <- raster::raster(g_map_lin)
raster::crs(g_map_lin) <- sp::CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
pal1 <- colorNumeric(pals::parula(200), raster::values(g_map_lin), na.color = "transparent")

lin_crimestat_map <- leaflet() %>%
  addProviderTiles('Esri.WorldTopoMap', group = 'Topo') %>%
  addAwesomeMarkers(lng = -71.07357, lat = 42.41322, icon = awesomeIcons(
    icon = 'home', markerColor = 'green'), popup = 'Residence') %>%
  addRasterImage(g_map_lin, colors = pal1, opacity = 0.6) %>%
  addLegend(pal = pal1, values = raster::values(g_map_lin), title = 'Score') %>%
  addCircleMarkers(lng = desalvo$lon, lat = desalvo$lat, radius = 4, opacity = 1,
                   stroke = FALSE, fillOpacity = 0.75, weight = 2,
                   fillColor = "black")
lin_crimestat_map
```







```{r}
g_map
```

```{r}
library(raster)
writeRaster(g_map, filename = "cgt_rast.tiff", overwrite = TRUE)
writeRaster(g_map1, filename = "ne_rast.tiff", overwrite = TRUE)
writeRaster(g_map_lin, filename = "lin_rast.tiff", overwrite = TRUE)

```

```{r}
webshot::install_phantomjs()
```


```{r}

library(leaflet)
library(htmlwidgets)
library(webshot)
#install.packages("mapview")
library(mapview)

mapshot(cgt_map, file = "Rplot.png")

#saveWidget(cgt_map, "temp.html", selfcontained = FALSE)
#webshot("temp.html", file = "Rplot.png", cliprect = "viewport")
```



```{r}
write.csv(desalvo, file = "desalvo")
```





```{r}
library(xtable)
mean(cgt$sums)
mean(ne_1$sums)
mean(linear$sums)

k = data.frame("Methods" = c("Rossmo's Exponential", "Negative Exponential", "Linear"),"Raster_Means" = c(mean(cgt$sums),mean(ne_1$sums),mean(linear$sums)), "Score_value_for_DeSalvo_House" = c(8.52109, 2.06329, 19.29897), "Standard_dev" = c(sd(cgt$sums), sd(ne_1$sums), sd(linear$sums)), "z-score" = c( (8.52109 - mean(cgt$sums))/sd(cgt$sums), (2.06329 - mean(ne_1$sums))/sd(ne_1$sums), (19.29897 - mean(linear$sums))/sd(linear$sums))
)

xtable(k)
```

```{r}
citation("rgeoprofile")
```


Rossmo's = 8.52109
NE = 2.06329
linear = 19.29897






